name: Docker Hello World

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor

jobs:
  hello-docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write           # Necessary to create attestations
      attestations: write       # Necessary to push attestations to GH account
    env:
      DOCKER_REPO: 'evidence-demo-docker-dev'
      IMAGE_NAME: 'github-hello-world:${{ github.run_number }}'
      JF_USERNAME: 'avishayh'
      JF_URL: ${{ vars.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_PROJECT: "default"
#      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
    - name: Authenticate Docker
      uses: docker/login-action@v3.4
      with:
          registry: ${{ env.JF_URL }}
          username: ${{ env.JF_USERNAME }}
          password: ${{ env.JF_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
      with:
        use: true
        platforms: linux/amd64,linux/arm64
        install: true

