name: Hello World

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor
  pull_request:
    branches:
      - main  # Change this to the branch for PRs

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install JFrog CLI
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        jf --version        

    - name: Verify JFrog CLI Installation
      run: | 
        

