name: Hello World

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor
  pull_request:
    branches:
      - main  # Change this to the branch for PRs

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write       # Necessary to create attestations
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install JFrog CLI
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        jf --version        
        sha2sum=$(sha256sum $GITHUB_WORKSPACE/README.md | awk '{print $1}')
        echo "SHA256: $sha2sum"
        echo $ACTIONS_ID_TOKEN_REQUEST_URL = $ACTIONS_ID_TOKEN_REQUEST_URL
        #curl $ACTIONS_ID_TOKEN_REQUEST_URL
        echo "ID_TOKEN=${{ steps.oidc.outputs.id_token }}" >> $GITHUB_ENV
        echo ID_TOKEN=$ID_TOKEN

    - name: Verify before attestations
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ./README.md


