name: Hello World

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor
  pull_request:
    branches:
      - main  # Change this to the branch for PRs

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write           # Necessary to create attestations
      attestations: write       # Necessary to push attestations to GH account
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ vars.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - name: Push To Artifactory
      id: build
      env:
        ARTIFACT_PATH: "dev-generic-local/github-example/README.md"
      run: |
        #upload to artifactory using jfrog cli
        jf rt u README.md ${{ env.ARTIFACT_PATH }} --detailed-summary | tee upload-summary.json
        jf --version
        # storing in output for later use
        sha256=$(jq -r '.files[0].sha256' upload-summary.json)
        echo "digest=$sha256" >> $GITHUB_OUTPUT
        echo "artifact_path=${{ env.ARTIFACT_PATH }}" >> $GITHUB_OUTPUT

    - name: Create build-provenance attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ vars.JF_URL }}/artifactory/${{ steps.build.outputs.artifact_path }}
        subject-digest: "sha256:${{ steps.build.outputs.digest }}"

#        JF-URL: {{vars.ARITFACTORY_URL}}
#        artifactory-path: $ARTIFACTORY_PATH


#Github
#POST $JF_URL/evidence/api/v1/sigstore-bundle/
#{
#   subject: "$ARTIFACTORY_PATH",
#   sigstore-bundle: {
#      #content of the sigstore bundle
#   }
#}
