name: Hello World

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor
  pull_request:
    branches:
      - main  # Change this to the branch for PRs

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write           # Necessary to create attestations
      attestations: write       # Necessary to push attestations to GH account
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ vars.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - name: Push To Artifactory
      id: build
      env:
        ARTIFACT_PATH: "dev-generic-local/github-example/README.md"
      run: |
        jf --version
        #upload to artifactory using jfrog cli
        jf rt u README.md ${{ env.ARTIFACT_PATH }} --details-summary > upload-summary.json
        
        # storing in output for later use
        sha256=$(jq -r '.files[0].sha256' upload-summary.json)
        echo "digest=$sha256" >> $GITHUB_OUTPUT
        echo "artifact_path={{ env.ARTIFACT_PATH }}" >> $GITHUB_OUTPUT

    - name: Create build-provenance attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ vars.JF_URL }}/${{ steps.build.outputs.artifact_path }}
        subject-digest: ${{ steps.build.outputs.digest }}
#        subject-path: ./README.md

#    - name: Install JFrog CLI
#      run: |
#        curl -fL https://install-cli.jfrog.io | sh
#        jf --version
#        sha2sum=$(sha256sum $GITHUB_WORKSPACE/README.md | awk '{print $1}')
#        echo "SHA256: $sha2sum"
#        env | base64
#        echo ACTIONS_ID_TOKEN_REQUEST_URL = $ACTIONS_ID_TOKEN_REQUEST_URL
#        echo ACTIONS_ID_TOKEN_REQUEST_TOKEN = ACTIONS_ID_TOKEN_REQUEST_TOKEN
#        curl $ACTIONS_ID_TOKEN_REQUEST_URL?audience=sigstore
#        #echo "ID_TOKEN=${{ steps.oidc.outputs.id_token }}"
#        #echo "ID_TOKEN=${{ steps.oidc.outputs.id_token }}" >> $GITHUB_ENV
#        #echo ID_TOKEN=$ID_TOKEN
#        #echo PRIVATE_KEY= "${{ secrets.PRIVATE_KEY }}"
#        #find /home/runner/work/_temp/
#        #echo GITHUB_ENV=$GITHUB_ENV
#        #ls -la /home/runner/work/_temp/_runner_file_commands
#        #ls -l $GITHUB_ENV
#        #find $GITHUB_ENV | xargs cat
#
#        dir=/home/runner/work/_temp/
#        echo "Listing files in: $dir"
#        ls $dir
#        cd /home/runner/work/_temp/_runner_file_commands
#        ls | grep save_state | xargs cat
#


#        JF-URL: {{vars.ARITFACTORY_URL}}
#        artifactory-path: $ARTIFACTORY_PATH


#Github
#POST $JF_URL/evidence/api/v1/sigstore-bundle/
#{
#   subject: "$ARTIFACTORY_PATH",
#   sigstore-bundle: {
#      #content of the sigstore bundle
#   }
#}
